version: '2'
services:
  web:
    image: pyflask
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "5000:5000"
    volumes:
     -  ./app:/app
  redis:
    image: "redis:alpine"